name: Build

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'extras/images/**'

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "macOS",
            os: macos-latest,
            artifact: "macos"
          }
        - {
            name: "Linux",
            os: ubuntu-latest,
            artifact: "linux"
          }

    steps:
      - uses: actions/checkout@v4

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.30.0"

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: "1.13.1"

      - name: Install Linux Dependencies
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev libbluetooth-dev

      - name: Verify
        run: |
          cmake --version
          ninja --version

      - name: Build
        run: |
          rm -rf build
          cmake -B build . -G Ninja -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS=ON -DENABLE_ASAN=OFF -DBUILD_EXECUTABLE=OFF
          cmake --build build
          cd build && ctest --output-on-failure --verbose

      - name: Package
        run: |
          cd build && cpack -G ZIP

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.artifact }}
          path: build/*.zip
          retention-days: 30
